import { GoogleGenAI, Modality, Type } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

export interface ResearchResult {
  summary: string;
  sources: { uri: string; title: string; }[];
}

export const generatePostIdeas = async (topic: string): Promise<string[]> => {
  try {
    const prompt = `Generate 5 engaging blog post titles about "${topic}".`;
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            ideas: {
              type: Type.ARRAY,
              description: "A list of 5 blog post titles.",
              items: {
                type: Type.STRING,
              },
            },
          },
          required: ["ideas"],
        },
      },
    });
    const text = response.text.trim();
    const result = JSON.parse(text);
    return result.ideas || [];
  } catch (error) {
    console.error("Error generating post ideas:", error);
    throw new Error("Failed to generate ideas. Please try again.");
  }
};

export const generatePostContent = async (title: string): Promise<string> => {
  try {
    const prompt = `Write a compelling and well-structured blog post about "${title}". The post should be at least 4 paragraphs long and written in Markdown format. Include headings, lists, or bold text to improve readability.`;
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error("Error generating post content:", error);
    throw new Error("Failed to generate content. Please try again.");
  }
};

export const generatePostImage = async (prompt: string): Promise<string> => {
  try {
    const fullPrompt = `Create a visually stunning and professional blog header image representing the concept of: "${prompt}". Minimalist, digital art style.`;
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: fullPrompt }],
      },
      config: {
          responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content.parts || []) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
      }
    }
    throw new Error("No image was generated by the API.");
  } catch (error) {
    console.error("Error generating post image:", error);
    throw new Error("Failed to generate image. Please try again.");
  }
};

export const researchTopic = async (topic: string): Promise<ResearchResult> => {
  try {
    const prompt = `Provide a concise research summary on the topic: "${topic}". Focus on key facts, recent developments, and important concepts. Format the output in Markdown.`;
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        tools: [{ googleSearch: {} }],
      },
    });

    const summary = response.text;
    const rawChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
    
    // Fix: Explicitly type `sources` to resolve an inference issue where `uniqueSources`
    // was being typed as `unknown[]`, causing a type mismatch on the return value.
    const sources: { uri: string; title: string; }[] = rawChunks
      .map((chunk: any) => chunk.web)
      .filter(Boolean)
      .map((web: any) => ({ uri: web.uri, title: web.title || web.uri }));
    
    const uniqueSources = Array.from(new Map(sources.map(item => [item.uri, item])).values());

    return { summary, sources: uniqueSources };
  } catch (error) {
    console.error("Error researching topic:", error);
    throw new Error("Failed to perform research. Please try again.");
  }
};